jobs:
  - name: nginx-mani
    type: manifest
    steps:
      - GET: nginx-image
      - GET: nginx-params
      - GET: nginx-opts
      
  - name: simple-mani
    type: manifest
    steps:
      - GET: simple-image
      - GET: simple-params
      - GET: simple-opts

  - name: ecs-beta
    type: ecsDeploy
    steps:
      - GET: nginx-mani
      - GET: simple-mani
      - GET: betaReplicas
      - GET: myEcsCluster
      - GET: betaParams
      - GET: betaOpts
      - GET: kickstartBeta
      
#  - name: dcl-prod
#    type: dclDeploy
#    steps:
#      - GET: ecs-beta
#        trigger: false
#      - GET: prodReplicas
#      - GET: myDclCluster
#      - GET: prodParams
#      - GET: prodOpts
#      - GET: kickstartProd

  - name: runSimpleServerCI
    type: runCI
    steps:
      - GET: simpleCI
#      - PUT: simple-image
