jobs:
  - name: simple-prod-mani-piiq
    type: manifest
    flags:
      - piiq
    steps:
      - IN: simple-image-prod-piiq
      - IN: simple-opts-prod-piiq
      - IN: simple-params-piiq
      - IN: prodTrigger-piiq

  - name: simple-int-mani-piiq
    type: manifest
    flags:
      - piiq
    steps:
      - IN: simple-image-int-piiq
      - IN: simple-opts-int-piiq
      - IN: simple-params-piiq

  - name: ecs-int-dep-piiq
    type: deploy
    flags:
      - piiq
    steps:
      - IN: intParams-piiq
      - IN: intReplicas-piiq
      - IN: simple-int-mani-piiq
      - IN: myEcsCluster-piiq

  - name: ecs-prod-dep-piiq
    type: deploy
    flags:
      - piiq
    steps:
      - IN: prodParams-piiq
      - IN: prodReplicas-piiq
      - IN: simple-prod-mani-piiq
      - IN: myEcsCluster-piiq


#  - name: ddc-test
#    type: ddcDeploy
#    options:
#      deployMethod: blueGreen
#    steps:
#      - IN: simple-mani
#      - IN: myDdcCluster
#      - IN: betaReplicas
#      - IN: betaParams
#      - IN: betaOpts
#      - TASK: managed

  # - name: testRelease
  #   type: release
  #   steps:
  #     - IN: testVer
  #     - IN: simple-mani
  #     - TASK: managed
  #
  # - name: testRelease2
  #   type: release
  #   steps:
  #     - IN: testVer2
  #     - IN: simple-mani

#  - name: dcl-prod
#    type: dclDeploy
#    steps:
#      - IN: ecs-beta
#        trigger: false
#      - IN: prodReplicas
#      - IN: myDclCluster
#      - IN: prodParams
#      - IN: prodOpts
#      - IN: prodTrigger
#      - TASK: managed

  # - name: prodYmlSync
  #   type: rSync
  #   steps:
  #     - IN: myProdSyncRepo
  #     - IN: prodTrigger
