jobs:
  - name: simple-mani
    type: manifest
    steps:
      - IN: simple-image
      - IN: simple-params
      - IN: simple-opts
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

  - name: staging
    type: ecsDeploy
    steps:
      - IN: stagingParams
      - IN: stagingOpts
      - IN: simple-mani
      - IN: simpleReplicas
      - IN: ecsStaging
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

#  - name: stagingRelease
#    type: release
#    steps:
#      - IN: releaseTrigger
#      - IN: stagingVer
#        trigger: false
#      - IN: staging
#        trigger: false
#    on_success:
#      - NOTIFY: stagingSlack
#    on_failure:
#      - NOTIFY: stagingSlack

  - name: prodBlueDeploy
    type: ecsDeploy
    steps:
      - IN: blueTrigger
      - IN: prodParams
        trigger: false
      - IN: prodOpts
        trigger: false
      - IN: stagingRelease
        trigger: false
      - IN: prodSimpleReplicas
        trigger: false
        applyTo:
          - simple-image
      - IN: ecsProduction
        trigger: false
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: prodGreenDeploy
    type: ecsDeploy
    steps:
      - IN: greenTrigger
      - IN: prodParams
        trigger: false
      - IN: prodOpts
        trigger: false
      - IN: stagingRelease
        trigger: false
      - IN: prodSimpleReplicas
        trigger: false
        applyTo:
          - simple-image
      - IN: ecsProduction
        trigger: false
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: runSimpleServerCI
    type: runCI
    steps:
      - IN: simple-repo
      - TASK: managed
      - OUT: simple-image
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack
