jobs:

  - name: myCustomDeployment
    type: runCLI
    steps:
      - IN: MyAwsConfig
      - IN: MyStaticTaskDefRepo
      - TASK:
        - script: aws ecs describe-clusters
        #- script: aws ecs register-task-definition --cli-input-json file://
        #- script: aws ecs create-service --cluster cluster-test-1 --service-name ${JOB_NAME}
