jobs:
  - name: MyNginxManifest
    type: manifest
    steps:
      - IN: MyNginxImage

  - name: MyRedisManifest
    type: manifest
    steps:
      - IN: MyRedisImage


  - name: DeployNginx
    type: deploy
    steps:
      - IN: MyECSCluster
      - IN: MyNginxManifest

  - name: DeployRedis
    type: deploy
    steps:
      - IN: MyECSCluster
      - IN: MyRedisManifest
