jobs:
  - name: runShCheck
    type: runSh
    steps:
      - IN: stagingTrigger-runShSample
      - TASK:
        - script: ls -latr
        - script: find . -not -path '*/\.*'
        - script: ./script.sh
        - script: source script.sh

    on_failure:
      - NOTIFY: stagingSlack-runShSample
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
      - NOTIFY: stagingSlack-runShSample
