jobs:
  ##########################
  # Basic jobs configuration
  ##########################

  - name: MyFirstManifest
    type: manifest
    steps:
      - IN: MyAppImage

  - name: DeployTo_cluster-test-1
    type: deploy
    steps:
      - IN: MyECSCluster
      - IN: MyFirstManifest
