jobs:
  - name: nginx-mani
    type: manifest
    steps:
      - GET: nginx-image
      - GET: nginx-params
      - GET: nginx-opts
      
  - name: simple-mani
    type: manifest
    steps:
      - GET: simple-image
      - GET: simple-params
      - GET: simple-opts

  - name: ecs-beta
    type: ecsDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: nginx-mani
      - GET: simple-mani
      - GET: betaReplicas
      - GET: myEcsCluster
      - GET: betaParams
      - GET: betaOpts
      - GET: betaTrigger
      
  - name: testRelease
    type: release
    options:
      action: minor
    steps:
      - GET: testVer
      - GET: simple-mani
      
  - name: testRelease2
    type: release
    options:
      action: minor
    steps:
      - GET: testVer2
      - GET: simple-mani
      
#  - name: dcl-prod
#    type: dclDeploy
#    steps:
#      - GET: ecs-beta
#        trigger: false
#      - GET: prodReplicas
#      - GET: myDclCluster
#      - GET: prodParams
#      - GET: prodOpts
#      - GET: prodTrigger

  - name: runSimpleServerCI
    type: runCI
    steps:
      - GET: simpleCIsyncRepo
      - PUT: simple-image
      
  - name: prodYmlSync
    type: rSync
    steps:
      - GET: myProdSyncRepo
