jobs:
  - name: deploy-simpleEbApp-eb
    type: runSh
    flags:
      - eb
    steps:
      - IN: myAwsCredentials
      - IN: simple-repo-eb
        switch: off
      - IN: simple-image-eb
      - TASK:
        - script: sudo apt-get install -y jq tree
        - script: pip install --upgrade --user awsebcli
        # - script: tree -f IN/myAwsCredentials/
        - script: source IN/myAwsCredentials/integration.env # add the credentials to the environment
        # - script: tree -f IN/simple-image-eb/
        - script: cat IN/simple-image-eb/version.json | jq '.'
        - script: IMAGE_NAME=$(jq -r '.sourceName' IN/simple-image-eb/version.json)
        - script: IMAGE_TAG=$(jq -r '.version.versionName' IN/simple-image-eb/version.json)
        - script: echo "pushing $IMAGE_NAME:$IMAGE_TAG to beanstalk"
        # - script: tree -f IN/simple-repo-eb/
        - script: DOCKERRUN_PATH=IN/simple-repo-eb/gitRepo/
        - script: mv $DOCKERRUN_PATH/Dockerrun.aws.json /tmp/Dockerrun.tmp
        - script: cat /tmp/Dockerrun.tmp | sed 's/<IMAGE_NAME>/"$IMAGE_NAME"/' | sed 's/<TAG>/"$IMAGE_TAG"/' > $DOCKERRUN_PATH/Dockerrun.aws.json
        - script: cat $DOCKERRUN_PATH/Dockerrun.aws.json
