jobs:
  - name: simple-mani
    type: manifest
    steps:
      - GET: simple-image
      - GET: simple-params
      - GET: simple-opts
      - GET: betaTrigger

  - name: staging
    type: ecsDeploy
    steps:
      - GET: stagingParams
      - GET: stagingOpts
      - GET: simple-mani
      - GET: stagingReplicas
      - GET: ecsStaging
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

  - name: stagingRelease
    type: release
    steps:
      - GET: stagingVer
        trigger: false
      - GET: staging
        trigger: false
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

  - name: prodBlueDeploy
    type: ecsDeploy
    steps:
      - GET: blueTrigger
      - GET: prodParams
        trigger: false
      - GET: prodOpts
        trigger: false
      - GET: stagingRelease
        trigger: false
      - GET: prodSimpleReplicas
        trigger: false
        applyTo:
          - simple-image
      - GET: ecsProduction
        trigger: false
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: prodGreenDeploy
    type: ecsDeploy
    steps:
      - GET: greenTrigger
      - GET: prodParams
        trigger: false
      - GET: prodOpts
        trigger: false
      - GET: stagingRelease
        trigger: false
      - GET: prodSimpleReplicas
        trigger: false
        applyTo:
          - simple-image
      - GET: ecsProduction
        trigger: false
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: runSimpleServerCI
    type: runCI
    steps:
      - GET: simple-repo
      - TASK: managed
      - PUT: simple-image
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack
