jobs:
  - name: simple-mani-runShSample
    type: manifest
    flags:
      - runShSample
    steps:
      - IN: simple-image-runShSample
      - IN: myParams-runShSample

  - name: simple-release-runShSample
    type: release
    flags:
      - runShSample
    steps:
      - IN: simple-mani-runShSample
      - IN: simple-version-runShSample
      - TASK: managed
        bump: patch

  - name: runShCheck-runShSample
    type: runSh
    flags:
      - runShSample
    steps:
      - IN: stagingTrigger-runShSample
      - IN: simple-release-runShSample
      - OUT: testOutImage
      - TASK:
        - script: echo "resource ID is $RESOURCE_ID"
        - script: echo "versionName=blah" > $RUNSHCHECKRUNSHSAMPLE_PATH/state/runShCheck-runShSample.env
#        - script: apt-get install -y tree jq unzip
#        - script: echo 'which aws?' && which aws || true
#        - script: cat /build/message.json | jq '.'
#        - script: echo 'about to install awscli'
#        - script: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
#        - script: unzip awscli-bundle.zip
#        - script: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
#        - script: echo 'which aws?' && which aws || true
#        - script: aws --version
#        - script: tree -F
#        - script: MANIFESTS=$(cat IN/simple-release-runShSample/release/manifests.json | jq -r)
#        - script: echo $MANIFESTS
#        - script: RELEASE=$(cat IN/simple-release-runShSample/release/release.json)
#        - script: echo $RELEASE

        #- script: ./script.sh
        #- script: source script.sh

    on_failure:
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
