jobs:
  - name: simple-mani-runShSample
    type: manifest
    flags:
      - runShSample
    steps:
      - IN: simple-image-runShSample
      - IN: myParams-runShSample

  - name: kube-deploy-test-runshsample
    type: deploy
    flags:
      - runShSample
    steps:
      - IN: kube-cluster-runShSample
      - IN: simple-mani-runShSample

  - name: out-mani-runShSample
    type: manifest
    flags:
      - runShSample
    steps:
      - IN: simple-image-runShSample

  - name: test-mani-runShSample
    type: manifest
    flags:
      - runShSample
    steps:
      - IN: testOutImage-runShSample


  - name: simple-release-runShSample
    type: release
    flags:
      - runShSample
    steps:
      - IN: simple-mani-runShSample
      - IN: simple-version-runShSample
      - TASK: managed
        bump: patch

  - name: runCLItest-runShSample
    type: runCLI
    flags:
      - runShSample
    steps:
      - IN: kube-cli-config-runShSample
      - TASK:
        - script: kubectl get pods --all-namespaces

  - name: runShCheck-runShSample
    type: runSh
    flags:
      - runShSample
    steps:
      - IN: stagingTrigger-runShSample
      - IN: simple-release-runShSample
      - IN: myRepo-runShSample
      - IN: myParams-runShSample
      - OUT: testOutImage-runShSample
      - OUT: out-mani-runShSample
      - TASK:
        - script: echo "resource ID is $RESOURCE_ID"
        - script: echo "versionName=$BUILD_NUMBER" > /build/state/testOutImage-runShSample.env
        - script: echo "versionName=$BUILD_NUMBER" > /build/state/runShCheck-runShSample.env
        - script: echo "extraProperty=$JOB_NAME" >> /build/state/testOutImage-runShSample.env
        - script: sudo apt-get install -y jq
        - script: ls -latr /build/state
        - script: cat /build/state/testOutImage-runShSample.env
        - script: cat /build/state/runShCheck-runShSample.env
        - script: ls -latr /build/IN/simple-release-runShSample/release
        #- script: cat $RUNSHCHECKRUNSHSAMPLE_PATH/message.json | jq '.'
        - script: cat $MYPARAMSRUNSHSAMPLE_PATH/params | jq '.'

    on_failure:
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
