jobs:
  - name: runShCheck
    type: runSh
    steps:
      - echo "hello world"
      - ls -latr
      - echo "script test 1"
      - ./script.sh
      - echo "script test 2"
      - source script.sh

    on_failure:
      - NOTIFY: stagingSlack-runShSample
