triggers:
  - name: blueTrigger
    type: trigger
    source:
      message: 'blue deployment'

  - name: greenTrigger
    type: trigger
    source:
      message: 'green deployment'

  - name: releaseTrigger
    type: trigger
    source:
      message: 'create release from staging cluster'

  - name: stagingTrigger
    type: trigger
    source:
      message: 'force a staging deploy'
