jobs:
  - name: simple-mani
    type: manifest
    steps:
      - IN: stagingTrigger
      - IN: simple-params
      - IN: simple-image
        versionName: master.58
      - IN: simple-opts
    on_failure:
      - NOTIFY: stagingSlack

  - name: staging-dep
    type: deploy
    steps:
      - IN: simple-mani
      - IN: stagingOpts
      - IN: stagingParams
      - IN: simpleReplicas
      - IN: gkeStaging
      # - IN: stagingLoadBalancer
      #   applyTo:
      #    - manifest: simple-mani
      #      image: simple-image
      #      port: 8888
      - TASK: managed
        deployMethod: blueGreen
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

  - name: stagingRelease
    type: release
    steps:
      - IN: releaseTrigger
      - IN: stagingVerBase
        switch: off
      - IN: staging-dep
        switch: off
    on_failure:
      - NOTIFY: stagingSlack

  - name: prodBlue
    type: deploy
    steps:
      - IN: blueTrigger
      - IN: stagingRelease
        switch: off
      - IN: prodOpts
        switch: off
      - IN: prodParams
        switch: off
      - IN: prodSimpleReplicas
        switch: off
        applyTo:
          - simple-image
      - IN: ecsProduction
        switch: off
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: prodSlack
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: prodGreen
    type: deploy
    steps:
      - IN: greenTrigger
      - IN: stagingRelease
        switch: off
      - IN: prodOpts
        switch: off
      - IN: prodParams
        switch: off
      - IN: prodSimpleReplicas
        switch: off
        applyTo:
          - simple-image
      - IN: ecsProduction
        switch: off
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: prodSlack
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack
