jobs:
  - name: simple-mani-release
    type: manifest
    flags:
      - release
    steps:
      - IN: stagingTrigger-release
      - IN: simple-params-release
      - IN: simple-image-release
      - IN: simple-opts-release

  - name: nginx-mani-release
    type: manifest
    flags:
      - release
    steps:
      - IN: stagingTrigger-release
      - IN: nginx-image-release
      - IN: nginx-params-release
      - IN: nginx-opts-release

  - name: staging-release-A-release
    type: release
    flags:
      - release
    steps:
      - IN: stagingVersion-release
      - IN: simple-mani-release
      - IN: nginx-mani-release
      - TASK: managed
        bump: rc

  - name: staging-release-B1-release
    type: release
    flags:
      - release
    steps:
      - IN: stagingVersion-release
      - IN: simple-mani-release

  - name: staging-release-B2-release
    type: release
    flags:
      - release
    steps:
      - IN: stagingVersion-release
      - IN: nginx-mani-release

  - name: prod-release-A-release
    type: release
    flags:
      - release
    steps:
      - IN: prodVersion-release
      - IN: staging-release-A-release
        switch: off
      - TASK: managed
        bump: patch

  - name: prod-release-B-release
    type: release
    flags:
      - release
    steps:
      - IN: prodVersion-release
      - IN: staging-release-B1-release
        switch: off
      - IN: staging-release-B2-release
        switch: off
