jobs:
  - name: runShCheck
    type: runSh
    steps:
      - IN: stagingTrigger-runShSample
      - IN: myParams
      - TASK:
        - script: ls -latr
        - script: find . -not -path '*/\.*'
        - script: cd ./IN/myParams/ && cat version.json || true
        - script: cd ./IN/myParams/params/ && cat version.json || true

        #- script: ./script.sh
        #- script: source script.sh

    on_failure:
      - NOTIFY: stagingSlack-runShSample
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
      - NOTIFY: stagingSlack-runShSample
