triggers:
  - name: betaTrigger
    type: trigger
    version:
      message: 'try this again 5'
      
  - name: noFirstTimeTrigger3
    type: trigger
    version:
      message: 'lets do this part 2'
      
  - name: prodTrigger
    type: trigger
    version:
      message: 'test'
      
  - name: triggertest1
    type: trigger
    version:
      message: 'ecs deploy again'
      
  - name: triggertest2
    type: trigger
    version:
      counter: 1
      
