jobs:
  - name: simple-mani-deploy
    type: manifest
    flags:
      - deploy
    steps:
      - IN: stagingTrigger-deploy
      - IN: simple-params-deploy
      - IN: simple-image-deploy
      - IN: simple-opts-deploy

  - name: nginx-mani-deploy
    type: manifest
    flags:
      - deploy
    steps:
      - IN: stagingTrigger-deploy
      - IN: nginx-image-deploy
      - IN: nginx-params-deploy
      - IN: nginx-opts-deploy

  - name: staging-deploy-A-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: stagingVersion-deploy
      - IN: simple-mani-deploy
      - IN: nginx-mani-deploy
      - IN: myDdcCluster

  - name: staging-deploy-B1-deploy
    type: deploy
    flags:
      - deploy
    steps:
      - IN: stagingVersion-deploy
      - IN: simple-mani-deploy
      # - IN: nginx-mani-deploy
      - IN: myDdcCluster

  # - name: staging-deploy-B2-deploy
  #   type: deploy
  #   flags:
  #     - deploy
  #   steps:
  #     - IN: stagingVersion-deploy
  #     - IN: nginx-mani-deploy
  #     - IN: myDdcCluster

  # - name: prod-deploy-A-deploy
  #   type: deploy
  #   flags:
  #     - deploy
  #   steps:
  #     - IN: prodVersion-deploy
  #     - IN: staging-deploy-A-deploy
  #       switch: off
  #     - IN: myDdcCluster
  #
  # - name: prod-deploy-B-deploy
  #   type: deploy
  #   flags:
  #     - deploy
  #   steps:
  #     - IN: prodVersion-deploy
  #     - IN: staging-deploy-B1-deploy
  #       switch: off
  #     - IN: staging-deploy-B2-deploy
  #       switch: off
  #     - IN: myDdcCluster
