jobs:

  - name: myCustomDeployment
    type: runCLI
    flags:
      - docs
    steps:
      - IN: MyAwsConfig
      - IN: MyStaticTaskDefRepo
        switch: off
      - TASK:
        - script: aws ecs describe-clusters
        - script: cat ${MYSTATICTASKDEFREPO_STATE}/taskdefinitions/sample.json | jq '.'
        - script: aws ecs register-task-definition --cli-input-json ${MYSTATICTASKDEFREPO_PATH}/taskdefinitions/sample.json
        #- script: aws ecs create-service --cluster cluster-test-1 --service-name ${JOB_NAME}
