jobs:
  - name: simple-mani-runCLISample
    type: manifest
    flags:
      - runCLISample
    steps:
      - IN: simple-image-runCLISample
      - IN: myParams-runCLISample

  - name: out-mani-runCLISample
    type: manifest
    flags:
      - runCLISample
    steps:
      - IN: simple-image-runCLISample

  - name: test-mani-runCLISample
    type: manifest
    flags:
      - runCLISample
    steps:
      - IN: testOutImage-runCLISample


  - name: simple-release-runCLISample
    type: release
    flags:
      - runCLISample
    steps:
      - IN: simple-mani-runCLISample
      - IN: simple-version-runCLISample
      - TASK: managed
        bump: patch

  - name: runCLIaws-runCLISample
    type: runCLI
    flags:
      - runCLISample
    steps:
      - IN: myConfig-runCLIsample
      - IN: dockerconfig-runCLIsample
      - TASK:
        - script: aws ec2 describe-vpcs
#        - script: docker pull trriplejay/simpleserver:master.142
#        - script: docker push trriplejay/simpleserver:master.142
    on_success:
      - script: aws ec2 describe-vpcs
      #- script: docker push trriplejay/simpleserver:master.142
    on_failure:
      - script: aws ec2 describe-vpcs
      #- script: docker push trriplejay/simpleserver:master.142
    always:
      - script: aws ec2 describe-vpcs
      #- script: docker push trriplejay/simpleserver:master.142

  - name: runShaws-runCLISample
    type: runSh
    flags:
      - runCLISample
    steps:
      - IN: runCLIaws-runCLISample
      - IN: dockerconfig-runCLIsample
      - TASK:
        - script: aws ec2 describe-vpcs
    on_success:
      - script: aws ec2 describe-vpcs
    on_failure:
      - script: aws ec2 describe-vpcs
    always:
      - script: aws ec2 describe-vpcs

  - name: runShCheck-runCLISample
    type: runCLI
    flags:
      - runCLISample
    steps:
      - IN: stagingTrigger-runCLISample
      - IN: simple-release-runCLISample
      - IN: myConfig-runCLIsample
      - OUT: testOutImage-runCLISample
      - OUT: out-mani-runCLISample
      - TASK:
        - script: echo "resource ID is $RESOURCE_ID"
        - script: echo "versionName=$BUILD_NUMBER" > /build/state/testOutImage-runCLISample.env
        - script: echo "versionName=$BUILD_NUMBER" > /build/state/runShCheck-runCLISample.env
        - script: echo "extraProperty=$JOB_NAME" >> /build/state/testOutImage-runCLISample.env
        - script: sudo apt-get install -y jq
        - script: ls -latr /build/state
        - script: cat /build/state/testOutImage-runCLISample.env
        - script: cat /build/state/runShCheck-runCLISample.env
        - script: ls -latr /build/IN/simple-release-runCLISample/release
        - script: cat $RUNSHCHECKRUNCLISAMPLE_PATH/message.json | jq '.'
        - script: aws ec2 describe-vpcs

    on_failure:
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
