triggers:
  - name: betaTrigger
    type: trigger
    version:
      message: 'try this again 3'
      
  - name: prodTrigger
    type: trigger
    version:
      message: 'test'
      
  - name: triggertest1
    type: trigger
    version:
      message: 'ecs deploy'
      
  - name: triggertest2
    type: trigger
    version:
      counter: 1
      
