jobs:
  - name: runShCheck
    type: runSh
    steps:
      - IN: stagingTrigger-runShSample
      - IN: myParams
      - IN: simple-mani-runShSample
      - TASK:
        - script: sudo apt-get install -y tree
        - script: tree -F
        - script: cd ./IN/myParams/ && cat version.json || true
        - script: cd ./IN/simple-mani-runShSample/manifest && ls -latr

        #- script: ./script.sh
        #- script: source script.sh

    on_failure:
      - NOTIFY: stagingSlack-runShSample
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
      - NOTIFY: stagingSlack-runShSample


  - name: simple-mani-runShSample
    type: manifest
    steps:
      - IN: myParams
      - OUT: simple-image-runShSample
