jobs:
  - name: simple-manifest-ft
    type: manifest
    flags:
      - ft
    steps:
      - IN: simple-image-ft

  - name: deploy-test-env-ft
    type: deploy
    flags:
      - ft
    steps:
      - IN: simple-manifest-ft
      - IN: EcsFTCluster
      - TASK: managed
        deployMethod: replace #'upgrade' is recommended instead

  - name: simple-function-test-ft
    type: runSh
    flags:
      - ft
    steps:
      - IN: deploy-test-env-ft
      - IN: simple-repo-ft
        switch: off #changing repo shouldnt trigger test, only deploy should
      - IN: functionTestTrigger-ft #for manually triggering test
      - TASK:
        - script: sudo apt-get install -y tree jq
        - script: ./IN/simple-repo-ft/gitRepo/runFT.sh
