triggers:
  - name: betaTrigger
    type: trigger
    source:
      message: 'test ddc manifest 1'
      
  - name: prodTrigger
    type: trigger
    source:
      message: 'force prod deploy'
      
  - name: triggertest1
    type: trigger
    source:
      message: 'testing trigger in yml'
      
  - name: triggertest2
    type: trigger
    source:
      counter: 1
      
