triggers:
  - name: stagingTrigger-serialCheck
    type: trigger
    version:
      message: 'trigger 2 manifests at once. Triggered: 6'

  - name: runSh2Trigger-serialCheck
    type: trigger
    flags:
      - serialCheck
    version:
      message: 'update to trigger runSh2.'
      count: 2
