jobs:
  - name: nginx-mani-serialCheck
    type: manifest
    flags:
      - serialCheck
    steps:
      - IN: nginx-image-serialCheck
      - IN: nginx-opts-serialCheck

  - name: runSh1-serialCheck
    type: runSh
    flags:
      - serialCheck
    steps:
      - TASK:
        - script: pwd
        - script: sleep 120

  - name: runSh2-serialCheck
    type: runSh
    flags:
      - serialCheck
    steps:
      - TASK:
        - script: pwd
        - script: sleep 120
