jobs:
  - name: simple-mani
    type: manifest
    steps:
      - IN: stagingTrigger
      - IN: simple-params
      - IN: simple-image
      - IN: simple-opts
    on_failure:
      - NOTIFY: stagingSlack

  - name: nginx-mani
    type: manifest
    steps:
      - IN: stagingTrigger
      - IN: nginx-image
      - IN: nginx-params
      - IN: nginx-opts
    on_failure:
      - NOTIFY: stagingSlack

  - name: staging-dep
    type: deploy
    steps:
      - IN: simple-mani
      - IN: nginx-mani
      - IN: stagingParams
      - IN: stagingOpts
      - IN: simpleReplicas
      - IN: ecsStaging
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack


  - name: parallel-dep
    type: deploy
    steps:
      - IN: simple-mani
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: stagingSlack
    on_failure: stagingSlack
