jobs:
  - name: simple-mani-release
    type: manifest
    steps:
      - IN: stagingTrigger-release
      - IN: simple-params-release
      - IN: simple-image-release
      - IN: simple-opts-release
    on_failure:
      - NOTIFY: stagingSlack-release

  - name: nginx-mani-release
    type: manifest
    steps:
      - IN: stagingTrigger-release
      - IN: nginx-image-release
      - IN: nginx-params-release
      - IN: nginx-opts-release
    on_failure:
      - NOTIFY: stagingSlack-release

  - name: staging-release-A
    type: release
    steps:
      - IN: simple-mani-release
      - IN: nginx-mani-release

  - name: staging-release-B1
    type: release
    steps:
      - IN: simple-mani-release

  - name: staging-release-B2
    type: release
    steps:
      - IN: nginx-mani-release

  - name: prod-release-A
    type: release
    steps:
      - IN: staging-dep-A

  - name: prod-release-B
    type: release
    steps:
      - IN: staging-dep-B


  - name: staging-dep-A
    type: deploy
    steps:
      - IN: release-A
      - IN: simpleReplicas-release
      - IN: ecsStaging-release
      - TASK: managed
        deployMethod: upgrade
    on_failure:
      - NOTIFY: stagingSlack-release

  - name: staging-dep-B
    type: deploy
    steps:
      - IN: release-B1
      - IN: release-B2
      - IN: simpleReplicas-release
      - IN: ecsStaging-release
      - TASK: managed
        deployMethod: upgrade
    on_failure:
      - NOTIFY: stagingSlack-release


  - name: prod-dep-A
    type: deploy
    steps:
      - IN: prod-release-A
      - IN: ecsProduction-release
      - TASK: managed
        deployMethod: upgrade
    on_failure:
      - NOTIFY: stagingSlack-release

  - name: prod-dep-B
    type: deploy
    steps:
      - IN: prod-release-B
      - IN: ecsProduction-release
      - TASK: managed
        deployMethod: upgrade
    on_failure:
      - NOTIFY: stagingSlack-release
