jobs:
  - name: runShCheck
    type: runSh
    steps:
      - IN: stagingTrigger-runShSample
      - TASK:
        - SCRIPT: echo "hello world"
        - SCRIPT: ls -latr
        - SCRIPT: echo "script test 1"
        - SCRIPT: ./script.sh
        - SCRIPT: echo "script test 2"
        - SCRIPT: source script.sh

    on_failure:
      - NOTIFY: stagingSlack-runShSample
      - echo "something failed"
    on_success:
      - echo "yay it worked"
      - NOTIFY: stagingSlack-runShSample
