triggers:
  - name: blueTrigger
    type: trigger
    version:
      message: 'blue deployment'

#  - name: greenTrigger
#    type: trigger
#    version:
#      message: 'green deployment'

  - name: releaseTrigger
    type: trigger
    version:
      message: 'create release from staging cluster'

  - name: stagingTrigger
    type: trigger
    version:
      message: 'force a staging deploy. triggered:3'
