jobs:
  - name: simple-mani
    type: manifest
    steps:
      - IN: stagingTrigger
      - IN: simple-params
      - IN: simple-image
      - IN: simple-opts
    on_failure:
      - NOTIFY: stagingSlack

  - name: staging-dep
    type: deploy
    steps:
      - IN: simple-mani
      - IN: stagingParams
      - IN: stagingOpts
      - IN: simpleReplicas
      - IN: ecsStaging
      # - IN: stagingLoadBalancer
      #   applyTo:
      #     - manifest: simple-mani
      #       image: simple-image
      #       port: 8888
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

  - name: stagingRelease
    type: release
    steps:
      - IN: releaseTrigger
      - IN: stagingVerBase
        switch: off
      - IN: staging-dep
        switch: off
    on_failure:
      - NOTIFY: stagingSlack

  - name: prodBlue
    type: deploy
    steps:
      - IN: blueTrigger
      - IN: stagingRelease
        switch: off
      - IN: prodOpts
        switch: off
      - IN: prodParams
        switch: off
      - IN: prodSimpleReplicas
        switch: off
        applyTo:
          - simple-image
      - IN: ecsProduction
        switch: off
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: prodSlack
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: prodGreen
    type: deploy
    steps:
      - IN: greenTrigger
      - IN: stagingRelease
        switch: off
      - IN: prodOpts
        switch: off
      - IN: prodParams
        switch: off
      - IN: prodSimpleReplicas
        switch: off
        applyTo:
          - simple-image
      - IN: ecsProduction
        switch: off
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: prodSlack
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: runSimpleServerCI
    type: runCI
    steps:
      - IN: simple-repo
      - TASK: managed
      - OUT: simple-image
    on_start:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack
