jobs:
  - name: simple-mani-runShSample
    type: manifest
    steps:
      - IN: simple-image-runShSample
      - IN: myParams-runShSample

  - name: simple-release-runShSample
    type: release
    steps:
      - IN: simple-mani-runShSample
      - IN: simple-version-runShSample
      - TASK: managed
        bump: patch

  - name: runShCheck-runShSample
    type: runSh
    steps:
      - IN: stagingTrigger-runShSample
      - IN: simple-release-runShSample
      - TASK:
        - script: apt-get install -y tree jq
        - script: echo 'which aws?' && which aws || true
        - script: echo 'about to install awscli'
        - script: apt-get install -y -f python3-urllib3=1.5 python3-chardet python3-requests python3-botocore awscli
        - script: echo 'which aws?' && which aws || true
        - script: aws --version
        - script: tree -F
        - script: MANIFESTS=$(cat IN/simple-release-runShSample/release/manifests.json | jq -r)
        - script: echo $MANIFESTS
        - script: RELEASE=$(cat IN/simple-release-runShSample/release/release.json)
        - script: echo $RELEASE

        #- script: ./script.sh
        #- script: source script.sh

    on_failure:
      - script: echo "something failed"
    on_success:
      - script: echo "yay it worked"
