triggers:
  - name: blueTrigger
    type: trigger
    source:
      message: 'blue deployment'

  - name: greenTrigger
    type: trigger
    source:
      message: 'green deployment'

  - name: stagingRelease
    type: trigger
    source:
      message: 'create release from staging cluster'
