jobs:
  - name: MyAppManifest
    type: manifest
    steps:
      - IN: MyNginxImage
      - IN: MyRedisImage


  - name: DeployApp
    type: deploy
    steps:
      - IN: MyECSCluster
      - IN: MyAppManifest
