jobs:
  - name: deploy-simpleEbApp-eb
    type: runSh
    flags:
      - eb
    steps:
      - IN: myAwsCredentials
      - IN: simple-repo-eb
        switch: off
      - IN: simple-image-eb
      - TASK:
        - script: ./IN/simple-repo-eb/gitRepo/depoyToEb.sh
