triggers:
  - name: betaTrigger
    type: trigger
    version:
      message: 'beta verify ddc'
      
  - name: prodTrigger
    type: trigger
    version:
      message: 'test'
      
  - name: triggertest1
    type: trigger
    version:
      message: 'here we go'
      
  - name: triggertest2
    type: trigger
    version:
      counter: 1
      
