jobs:

  - name: MyNginxManifest
    type: manifest
    steps:
      - IN: MyNginxImage

  - name: MyRedisManifest
    type: manifest
    steps:
      - IN: MyRedisImage

  - name: DeployTo_cluster-test-1
    type: deploy
    steps:
      - IN: MyECSCluster
      - IN: MyNginxManifest
      - IN: MyRedisManifest
