jobs:
  - name: simple-mani
    type: manifest
    steps:
      - IN: stagingTrigger
      - IN: simple-image
      - IN: simple-params
      - IN: simple-opts
    on_failure:
      - NOTIFY: stagingSlack

  - name: staging-dep
    type: deploy
    steps:
      - IN: stagingParams
      - IN: stagingOpts
      - IN: simple-mani
      - IN: simpleReplicas
      - IN: ecsStaging
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack

  - name: stagingRelease
    type: release
    steps:
      - IN: releaseTrigger
      - IN: stagingVerBase
        trigger: false
      - IN: staging-dep
        trigger: false
    on_failure:
      - NOTIFY: stagingSlack

  - name: prodBlue
    type: deploy
    steps:
      - IN: blueTrigger
      - IN: stagingRelease
        trigger: false
      - IN: prodParams
        trigger: false
      - IN: prodOpts
        trigger: false
      - IN: prodSimpleReplicas
        trigger: false
        applyTo:
          - simple-image
      - IN: ecsProduction
        trigger: false
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: prodSlack
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: prodGreen
    type: deploy
    steps:
      - IN: greenTrigger
      - IN: stagingRelease
        trigger: false
      - IN: prodParams
        trigger: false
      - IN: prodOpts
        trigger: false
      - IN: prodSimpleReplicas
        trigger: false
        applyTo:
          - simple-image
      - IN: ecsProduction
        trigger: false
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: prodSlack
    on_success:
      - NOTIFY: prodSlack
    on_failure:
      - NOTIFY: prodSlack

  - name: runSimpleServerCI
    type: runCI
    steps:
      - IN: simple-repo
      - TASK: managed
      - OUT: simple-image
    on_start:
      - NOTIFY: stagingSlack
    on_failure:
      - NOTIFY: stagingSlack
